apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Secure Web Page</title>
    </head>
    <body>
    <h1>Welcome to My Secure Web Page!</h1>
    <p>This page is served over HTTPS with a self-signed certificate!</p>
    </body>
    </html>