apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>My Web Page</title>
    </head>
    <body>
    <h1>Welcome to My Web Page!</h1>
    <p>This page is served from a Kubernetes ConfigMap!</p>
    </body>
    </html>